[package]
authors = ["Lucas Brendel <lucasbrendel@gmail.com>"]
edition = "2018"
name = "xmc4-hal"
version = "0.1.0"

[dependencies]
xmc4100 = { version = "0.3.0", optional = true }
xmc4200 = { version = "0.2.0", optional = true }
xmc4500 = { version = "0.2.0", optional = true }
xmc4700 = { version = "0.3.0", optional = true }
cortex-m = "0.6.1"
nb = "0.1.1"
cortex-m-rt = "0.6.7"

[features]
default = ["xmc4100"]
xmc41xx = ["xmc4100"]
xmc42xx = ["xmc4200"]
xmc45xx = ["xmc4500"]
xmc47xx = ["xmc4700"]

[dependencies.void]
default-features = false
version = "1.0.2"

[dependencies.cast]
default-features = false
version = "0.2.2"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.2"

[dev-dependencies]
panic-halt = "0.2.0"
panic-semihosting = "0.5.1"
panic-itm = "0.4.0"
cortex-m-rtfm = "0.4.0"
cortex-m-semihosting = "0.3.2"
enc28j60 = "0.2.0"
heapless = "0.5.1"
libm = "0.1.2"
mfrc522 = "0.2.0"
as-slice = "0.2.0"
serde_derive = "1.0.82"
serde-json-core = "0.0.1"
mpu9250 = "0.12.2"

[dev-dependencies.byteorder]
default-features = false
version = "1.2.7"

[dev-dependencies.cobs]
default-features = false
version = "0.1.3"

[dev-dependencies.crc16]
default-features = false
version = "0.4.0"

[dev-dependencies.either]
default-features = false
version = "1.5.0"

[dev-dependencies.jnet]
git = "https://github.com/japaric/jnet"
rev = "df96b408049ca952ad7844d6552e87cf8fc18d2a"

[dev-dependencies.serde]
default-features = false
version = "1.0.82"

