[package]
authors = ["Lucas Brendel <lucasbrendel@gmail.com>"]
edition = "2018"
name = "xmc4-hal"
version = "0.1.0"
readme = "README.md"
repository = "https://github.com/xmc-rs/xmc4-hal"
description = "Peripheral access API for XMC4 series microcontrollers"
documentation = "https://docs.rs/crate/xmc4-hal"
categories = [
    "embedded",
    "hardware-support",
    "no-std"
]
keywords = [
    "arm",
    "cortex-m",
    "hal",
    "xmc"
]

[package.metadata.docs.rs]
features = ["xmc41xx"]

[dependencies]
xmc4100 = { version = "0.3.0", optional = true }
xmc4200 = { version = "0.2.0", optional = true }
xmc4300 = { version = "0.1.0", optional = true }
xmc4400 = { version = "0.3.0", optional = true }
xmc4500 = { version = "0.3.0", optional = true }
xmc4700 = { version = "0.3.0", optional = true }
xmc4800 = { version = "0.2.0", optional = true }
cortex-m = "0.6.1"
nb = "0.1.2"
cortex-m-rt = "0.6.10"

[features]
device-selected = []
xmc41xx = ["xmc4100", "device-selected"]
xmc42xx = ["xmc4200", "device-selected"]
xmc43xx = ["xmc4300", "device-selected"]
xmc44xx = ["xmc4400", "device-selected"]
xmc45xx = ["xmc4500", "device-selected"]
xmc47xx = ["xmc4700", "device-selected"]
xmc48xx = ["xmc4800", "device-selected"]

[dependencies.void]
default-features = false
version = "1.0.2"

[dependencies.cast]
default-features = false
version = "0.2.2"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.3"

[dev-dependencies]
panic-halt = "0.2.0"
panic-semihosting = "0.5.3"
panic-itm = "0.4.1"
cortex-m-rtfm = "0.4.3"
cortex-m-semihosting = "0.3.5"
heapless = "0.5.1"
libm = "0.1.4"
as-slice = "0.2.0"

[dev-dependencies.byteorder]
default-features = false
version = "1.3.2"

[dev-dependencies.cobs]
default-features = false
version = "0.1.4"

[dev-dependencies.crc16]
default-features = false
version = "0.4.0"

[dev-dependencies.either]
default-features = false
version = "1.5.3"

[dev-dependencies.jnet]
git = "https://github.com/japaric/jnet"
rev = "df96b408049ca952ad7844d6552e87cf8fc18d2a"

