on:
  pull_request:
  push:
    branches:
      - master

name: bloat

jobs:
  cargo_bloat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 'stable'
          target: 'thumbv7em-none-eabihf'
      - name: Run cargo bloat
        uses: orf/cargo-bloat-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          bloat_args: "--features=xmc4200"
          tree_args: "--features=xmc4200"