on:
  push:
    branches-ignore:
      - 'dependabot/**'
name: Clippy
jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
            toolchain: 'stable'
            target: 'thumbv7em-none-eabihf'
            components: clippy
      - uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --features xmc41xx
