on: [push]

name: Coverage

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: test
          args: --no-fail-fast --features xmc41xx --tests --target x86_64-unknown-linux-gnu
        env:
          'CARGO_INCREMENTAL': '0'
          'RUSTFLAGS': '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off'
      - name: Code coverage
        id: coverage
        uses: actions-rs/grcov@v0.1.6
      - name: Coveralls upload
        uses: coverallsapp/github-action@v2.2.3
        with:
          path-to-lcov: ${{ steps.coverage.outputs.report }}
          github-token: ${{ secrets.github_token }}
