name: XMC Devices

on:
  push:
    branches:
    - master

jobs:
  build:
    strategy:
      matrix:
        device: ['xmc41xx', 'xmc42xx', 'xmc43xx', 'xmc44xx', 'xmc45xx', 'xmc47xx', 'xmc48xx']
    name: ${{ matrix.device }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 'stable'
            target: 'thumbv7em-none-eabi'
            override: true
      - name: Cargo Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target ${{ matrix.rust-target }} --features=${{ matrix.device }}
      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --target ${{ matrix.rust-target }} --features=${{ matrix.device }}
