name: Examples

on:
  push:
    branches:
    - master

jobs:
  build:
    strategy:
      matrix:
        device: ['xmc41xx', 'xmc42xx', 'xmc43xx', 'xmc44xx', 'xmc45xx', 'xmc47xx', 'xmc48xx']
    name: ${{ matrix.device }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
            toolchain: 'stable'
            target: 'thumbv7em-none-eabihf'
      - name: Cargo Build
        run: cargo build --examples --features=${{ matrix.device }}
