on: push
name: Format
jobs:
  rustfmt:
      name: Format
      runs-on: ubuntu-latest
      steps:
        - name: Checkout sources
          uses: actions/checkout@v4.1.1

        - name: Install nightly toolchain with rustfmt available
          uses: actions-rust-lang/setup-rust-toolchain@v1
          with:
            toolchain: nightly
            components: rustfmt
        - name: Run cargo fmt
          uses: actions-rust-lang/rustfmt@v1
