on: push
name: Format
jobs:
  rustfmt:
      name: Format
      runs-on: ubuntu-latest
      steps:
        - name: Checkout sources
          uses: actions/checkout@v4.1.1

        - name: Install nightly toolchain with rustfmt available
          uses: actions-rs/toolchain@v1.0.7
          with:
            profile: minimal
            toolchain: nightly
            override: true
            components: rustfmt

        - name: Run cargo fmt
          uses: actions-rs/cargo@v1.0.3
          with:
            command: fmt
            args: --all -- --check