name: Rust

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    strategy:
      matrix:
        rust-channel: [ 'stable', 'nightly' ]
        rust-target: [ 'x86_64-unknown-linux-gnu', 'thumbv7em-none-eabihf' ]
        device: ['xmc41xx', 'xmc42xx', 'xmc43xx', 'xmc44xx', 'xmc45xx', 'xmc47xx', 'xmc48xx']
    name: ${{ matrix.rust-channel }}-${{ matrix.rust-target }}-${{ matrix.device }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
            toolchain: ${{ matrix.rust-channel }}
            target: ${{ matrix.rust-target }}
      - name: Cargo Check
        run: cargo check --target ${{ matrix.rust-target }} --features=${{ matrix.device }}
      - name: Cargo Build
        run: cargo build --verbose --target ${{ matrix.rust-target }} --features=${{ matrix.device }}
