name: Test

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        rust-channel: [ 'stable', 'nightly' ]
        rust-target: [ 'x86_64-unknown-linux-gnu', 'thumbv7em-none-eabihf' ]
        device: ['xmc41xx', 'xmc42xx', 'xmc43xx', 'xmc44xx', 'xmc45xx', 'xmc47xx', 'xmc48xx']
    name: ${{ matrix.rust-channel }}-x86_64-unknown-linux-gnu-${{ matrix.device }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
            toolchain: ${{ matrix.rust-channel }}
            target: 'x86_64-unknown-linux-gnu'
      - name: Cargo Test
        run: cargo test --lib --target x86_64-unknown-linux-gnu --features ${{ matrix.device }}
