name: Todo

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: todo-actions
      uses: dtinth/todo-actions@v0.2.0

